modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="craftablelava" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Craftable Lava" #mandatory
credits="Thanks to Eric Creation for making the original mod" #optional
authors="RedRoseWarrior1" #optional
description='''
This mod makes lava craftable'''
[[dependencies.craftablelava]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.craftablelava]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
