modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"

[[mods]] #mandatory
modId="craftablelava" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
credits="Thanks to Eric Creation for making the original mod" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

[[dependencies.craftablelava]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.craftablelava]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"